name: Daily Dependency Update

on:
  schedule:
    - cron: '45 5 * * *' # Ejecutar todos los d√≠as a las 5:45 AM UTC

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: npx npm-check-updates -u

      - name: Configure Git
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          export CURRENT_DATE=$(date +'%Y-%m-%d')
          git add .
          git commit -m "Automated dependency update - $CURRENT_DATE"
          git push
